CREATE WAREHOUSE IF NOT EXISTS RAILWAY_WH
WITH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS RAILWAY_DB;

USE DATABASE RAILWAY_DB;

CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS STAGING;
CREATE SCHEMA IF NOT EXISTS MART;


CREATE ROLE IF NOT EXISTS RAILWAY_ROLE;

GRANT USAGE ON WAREHOUSE RAILWAY_WH TO ROLE RAILWAY_ROLE;
GRANT USAGE ON DATABASE RAILWAY_DB TO ROLE RAILWAY_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE RAILWAY_DB TO ROLE RAILWAY_ROLE;

GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE RAILWAY_DB TO ROLE RAILWAY_ROLE;

GRANT ROLE RAILWAY_ROLE TO USER 'xxxxx';